config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  resources :cleanings
  root 'dashboards#index'
  resources :reservations
  resources :listings
  resources :users
  resources :cleaning_tasks
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  enum type: { current_residence: 0, mailing_address: 1 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :expense
end

app/models/cleaning_task.rb
class CleaningTask < ApplicationRecord
  belongs_to :reservation
  belongs_to :listing
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :property
end

app/models/host.rb
class Host < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  extend FriendlyId
  has_many :reservations
  validates :name, :address, presence: true
  friendly_id :name, use: :slugged
  belongs_to :owner_id, optional: true, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :reservation
end

app/models/property.rb
class Property < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  has_one :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { "admin": 0, "owner": 1, "guest": 2 }

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def index; end
end

app/controllers/cleanings_controller.rb
class CleaningsController < ApplicationController
  include Pagy::Backend
  def index
    @cleanings = Cleaning.all
    @pagy, @records = pagy(@cleanings, items: @per_page)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include Pagy::Backend
  def index
    @per_page = params[:per_page].nil? ? 10 : params[:per_page]

    @todays_cleaning_tasks = CleaningTask.all
    @pagy, @records = pagy(@todays_cleaning_tasks, items: @per_page)
    AuthHostAway.run(data_type: params[:fetch_data]) if params[:fetch_data]
    @listtings = Listing.all
    # where(cleaning_date: Date.today..(Date.tomorrow + 5.days))
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include Pagy::Backend
  def index
    AuthHostAway.run(data_type: params[:fetch_data]) if params[:fetch_data]
    @per_page = params[:per_page].nil? ? 10 : params[:per_page]

    @listings = Listing.all
    @pagy, @records = pagy(@listings, items: @per_page)
  end

  def show
    @listing = Listing.friendly.find(params[:id])
    @reservations = @listing.reservations
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    respond_to do |format|
      if @listing.save!
        format.html { redirect_to listings_path, notice: 'Succefully created listing' }
      else
        format.html do
          redirect_to request.referrer, alert: "could not create new listing becuase #{@listing.joined_errors}"
        end
      end
    end
  end

  def update
    @listing = Listing.find(listing_params[:id])
    respond_to do |format|
      if @listing.update!
        format.html { redirect_to listing_path(@listing.id), notice: 'Succefully updated listing' }
      else
        format.html do
          redirect_to request.referrer, alert: "could not create new listing becuase #{@listing.joined_errors}"
        end

      end
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    respond_to do |format|
      if @listing.delete
        format.html { redirect_to listings_path, notice: 'Succefully deleted listing' }
      else
        format.html do
          redirect_to request.referrer, alert: "could not deleted listing becuase #{@listing.joined_errors}"
        end

      end
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:id, :name, :external_listing_name, :internal_listing_name, :description, :state,
                                    :city, :street, :address, :zipcode, :price, :bedrooms_number, :beds_number, :cleaning_fee, :bathrooms_number)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  include Pagy::Backend
  def index
    AuthHostAway.run(data_type: params[:fetch_data]) if params[:fetch_data]
    @reservastions = Reservation.all
    @per_page = params[:per_page].nil? ? 10 : params[:per_page]
    @pagy, @records = pagy(@reservastions, items: @per_page)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :internal_server_error }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cleanings/_table.html.haml
.xl:col-span-6.col-span-12.bg-white.text-black.my-3
  %div.text-black.bg-zinc-200.py-4.px-1
    .justify-between.flex
      .box-title.font-bold Cleaning
      %div
        %button.ti-btn.ti-btn-light.text-white.py-1.px-2.rounded.bg-zinc-800{:class => "!py-1 !px-2 !text-[0.75rem]", :type => "button"} View All
        %button.ti-btn.ti-btn-light.text-white.py-1.px-2.rounded.bg-zinc-800{:class => "!py-1 !px-2 !text-[0.75rem]", :type => "button"} Add Cleaning
    .box-body
      %ul.list-none.mb-0.personal-upcoming-events
        -@records.each do |res|
          %li.py-3
            .flex
              .me-2
                %span.avatar.avatar-rounded.bg-amber-600.py-2.px-3.rounded
                  %i{class:"fa-solid fa-hotel text-black"}
              .flex-grow.flex-col
                %span
                  %span.text-primary.font-semibold=(res.guest_name || "Guest Name")
                %div.flex
                  %span.block{:class => " text-[0.75rem]"} Arrival Date:
                  %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}=res.arrival_date
                  %span.block{:class => " text-[0.75rem]"} Departure Date:
                  %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}=res.departure_date
    %div.flex.justify-between
      %form{action: reservations_path, method: :get}
        %input{name: "tab", value: "expenses", type: "hidden"}/
        %select{name: "per_page", class: "form-select rounded-full border border-zinc-300 bg-white px-2 py-1 pr-6 hover:border-zinc-400 focus:border-primary dark:border-zinc-450 dark:bg-zinc-700 dark:hover:border-zinc-400 dark:focus:border-accent", data: {controller: "select-and-go", action: "change->select-and-go#choose"}}
          %option{value: 10, selected: @per_page == '10' ? 'selected' : false}
            10
          %option{value: 30, selected: @per_page == '30' ? 'selected' : false}
            30
          %option{value: 50, selected: @per_page == '50' ? 'selected' : false}
            50
      %span entries
    .flex.flex-col.justify-between.space-y-4.px-4.py-4.sm:flex-row.sm:items-center.sm:space-y-0.sm:px-5
      %div{class: "text-xs+"}
        = "#{@pagy.from} - #{@pagy.to} of #{@pagy.count} entries"

   

app/views/cleanings/index.html.haml
= render "shared/navbar"
= render "/cleanings/table"

app/views/dashboards/_cleaning_table.html.haml
%div.px-1.py-4
  .xl:col-span-12.col-span-12.text-zinc-800.bg-white{controller: "hello"}
    .box.custom-card.text-zinc-800
      .box-header.flex.justify-between.p-3
        .box-title Todays Cleanings Task
        .button   
          = link_to "Refresh Cleanings" , root_path(fetch_data: "cleanings"),  class: "py-2 px-1 bg-zinc-500 rounded text-white"
      .box-body{:class => "!p-0"}
        .table-responsive
          %table.table.whitespace-nowrap.min-w-full.mb-0.text-zinc-800
            %thead
              %tr
                %th.text-start{:scope => "col"} Status
                %th.text-start{:scope => "col"} Cleaning Date
                %th.text-start{:scope => "col"} Listing Name
                %th.text-start{:scope => "col"} Cleaning Fee
            %tbody.top-selling
              - cleaning_tasks.order(cleaning_date: :asc).each do |task|
                %tr.border-y.border-inherit.border-solid{:class => "dark:border-defaultborder/10"}
                  -listing = Listing.where(id: task.listing_id).first
                  %td.leading-none
                    %span.badge.rounded-lg.bg-gray-200.px-4.py-1{:class => "bg-success/10 !font-normal"}= (task.status || "None")
                  %td
                    %p.text-xs{data: { controller:'date-time-style', data: task.cleaning_date.to_i}}
                  %td= listing.name
                  %td
                    %span.font-semibold= number_to_currency(listing.cleaning_fee)
    =render partial: "/shared/pagination", locals: {per_page: @per_page, pagy: @pagy , url: root_path, objects: @cleaning_tasks}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Condos Management App
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css",
          :integrity => "sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==",
          :referrerpolicy => "no-referrer", :rel => "stylesheet"}/
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "main", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "all-themes", "inter-font", "data-turbo-track": "reload"
 
    -# = javascript_include_tag "application"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = javascript_importmap_tags
  %body.page.bg-gray-100
    %main
    -if current_user.present?
      = render "shared/navbar"
    %span.notice= notice
    %span.alert= alert
    = yield

app/views/layouts/login.html.haml
=link_to "Login" ,new_user_session_path
=link_to "Sign Up" ,new_user_registration_path ,class: "rounded bg-sky-500"

app/views/listings/_form.html.haml
= form_for listing, url:url, data: { turbo: false , class: 'space-y-6 bg-white p-6 rounded-lg shadow-md' } do |f|
  .grid.grid-cols-2.gap-4
    .form-group
      = f.label :name, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :name, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :external_listing_name, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :external_listing_name, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :internal_listing_name, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :internal_listing_name, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group.col-span-2
      = f.label :description, class: 'block text-sm font-medium text-zinc-800'
      = f.text_area :description, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 h-24'
  
    .form-group
      = f.label :state, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :state, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :city, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :city, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :street, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :street, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :address, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :address, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :zipcode, class: 'block text-sm font-medium text-zinc-800'
      = f.text_field :zipcode, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :price, class: 'block text-sm font-medium text-zinc-800'
      = f.number_field :price, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :bedrooms_number, class: 'block text-sm font-medium text-zinc-800'
      = f.number_field :bedrooms_number, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :beds_number, class: 'block text-sm font-medium text-zinc-800'
      = f.number_field :beds_number, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :cleaning_fee, class: 'block text-sm font-medium text-zinc-800'
      = f.number_field :cleaning_fee, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
    .form-group
      = f.label :bathrooms_number, class: 'block text-sm font-medium text-zinc-800'
      = f.number_field :bathrooms_number, class: 'text-zinc-800 mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
  
  .flex.justify-end.mt-4
    = f.submit 'Submit', class: 'px-4 py-2 bg-indigo-600 text-white rounded-lg shadow-md hover:bg-indigo-700'

app/views/listings/_table.html.haml
.xl:col-span-6.col-span-12.bg-white.text-black.my-3
  %div.text-black.bg-zinc-200.py-4.px-1
    .justify-between.flex
      .box-title.font-bold Listings
      %div
        = link_to "Add Listings", new_listing_url, class: "ti-btn ti-btn-light text-white py-1 px-2 rounded bg-zinc-800 !py-1 !px-2 !text-[0.75rem]"
        = link_to "Refresh listings",listings_url(fetch_data: "listings"),  class: " py-1 px-2 bg-zinc-500 rounded text-white"

    .box-body
      %ul.list-none.mb-0.personal-upcoming-events
        -@records.each do |lis|
          %li.py-3
            .flex
              .me-2
                %span.avatar.avatar-rounded.bg-amber-600.py-2.px-3.rounded
                  %i{class:"fa-solid fa-hotel text-black"}
              .flex-grow.flex-col
                %span
                  =link_to listing_path(lis.id) , class: "text-primary.font-semibold" do 
                    =(lis.name || "listing name")
                  %div.flex.justify-between
                    %div.flex
                      %span.block{:class => " text-[0.75rem]"}Address:
                      %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}=lis.address
                      %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}="#{lis.city}, #{lis.state} #{lis.zipcode}"
                      %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}="#{lis.city}, #{lis.state} #{lis.zipcode}"
                    -if current_user.admin?
                      %div
                        = button_to listing_path(lis.id), method: :delete, data: {turbo: false}, class: "py-2 px-3 rounded zinc-800 h-11 w-full font-medium text-pink-700  hover:bg-pink-700/20" do
                          Delete
    = render partial: "/shared/pagination", locals: {per_page: @per_page , pagy: @pagy , url: reservations_path ,objects: @listings}
    .flex.flex-col.justify-between.space-y-4.px-4.py-4.sm:flex-row.sm:items-center.sm:space-y-0.sm:px-5
      %div{class: "text-xs+"}
        = "#{@pagy.from} - #{@pagy.to} of #{@pagy.count} entries"

app/views/listings/edit.html.haml
= render partial: "form" ,locals: {url: listing_path(@listing.id), listing: @listing}

app/views/listings/index.html.haml
=render "listings/table"

app/views/listings/new.html.haml
= render partial: "form" ,locals: {url: listings_path, listing: @listing}

app/views/listings/show.html.haml
.main-content.text-zinc-800
  / Page Header
  .block.justify-between.page-header.md:flex
    %div
      %h3.font-semibold{:class => " text-[1.125rem]"}= @listing.name
      %h3.font-semibold{:class => " text-[1.125rem]"}= @listing.address
    %ol.whitespace-nowrap.min-w-0.flex.justify-between
      %li{:class => "text-[0.813rem] ps-[0.5rem] "}
        %a.flex.items-center.text-primary.truncate{:href => "javascript:void(0);"}
          Listings
          %i{class:"fa-solid fa-chevron-right"}
      %li.font-semibold.hover:text-primary{"aria-current" => "page", :class => ""} Reservetions
  / Page Header Close
  / Start::row-1
  .container
    %ul.timeline.list-none.text-defaulttextcolor{:class => "text-[0.813rem]"}
      - if @reservations.empty?
        No Upcoming Reservations
      -@reservations.each do |r|
        %li

          .timeline-icon
            %a{"aria-label" => "anchor", :href => "javascript:void(0);"}
          .timeline-body
            .flex.items-start.timeline-main-content.flex-wrap.mt-0
              .avatar.avatar-md.online.me-3.avatar-rounded.md:mt-0.mt-6
                %i{class:"fa-solid fa-square-h"}
              .flex-grow
                .flex.items-center
                  .sm:mt-0.mt-2
                    %p.mb-0.font-semibold{:class => "text-[.875rem]"}= r.guest_name
                    %p.mb-0{:class => ""} 
                      %span.badge.text-primary.font-semibold.mx-1{:class => "bg-primary/10"}
                      %span.badge.font-semibold.mx-1{:class => "bg-primary/10"}
                  .flex.flex-cols
                    .ms-auto
                      %span.ltr:float-right.rtl:float-left.badge.timeline-badge.whitespace-nowrap{:class => "!bg-light"} Departure Date:
                      %span.ltr:float-right.rtl:float-left.badge.timeline-badge.whitespace-nowrap{:class => "!bg-light"}= r.departure_date
                    .timeline-time
                      %span.time.inline-block Arrival Date
                      %span.date= r.arrival_date

app/views/reservations/_table.html.haml
.xl:col-span-6.col-span-12.bg-white.text-black.my-3
  %div.text-black.py-4.px-1
    .justify-between.flex
      .box-title.font-bold Reservations
      %div
        %button.ti-btn.ti-btn-light.text-white.py-1.px-2.rounded.bg-zinc-800{:class => "!py-1 !px-2 !text-[0.75rem]", :type => "button"} Add Reservation
        = link_to "Refresh Reservatio",reservations_url(fetch_data: "listings"),  class: " py-1 px-2 bg-zinc-500 rounded text-white"

    .box-body
      %ul.list-none.mb-0.personal-upcoming-events
        -@records.each do |res|
          %li.py-3
            .flex
              .me-2
                %span.avatar.avatar-rounded.bg-amber-600.py-2.px-3.rounded
                  %i{class:"fa-solid fa-hotel text-black"}
              .flex-grow.flex-col
                %span.flex.justify-between  
                  %span.text-primary.font-semibold=(res.guest_name || "Guest Name")
                  %div
                    %span Total
                    %span= res.total_price
                %div.flex
                  %span= Listing.where(hostaway_id: res.hostaway_reservation_id).first&.name
                  %span.block Arrival Date:
                  %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}=res.arrival_date
                  %span.block Departure Date:
                  %span.badge.text-primary.whitespace-nowrap{:class => "bg-primary/10"}=res.departure_date
      =render partial: "/shared/pagination", locals: {per_page: @per_page , pagy: @pagy , url: reservations_path ,objects: @records}

            
          
   

app/views/reservations/index.html.haml
= render "/reservations/table"

app/views/shared/_navbar.html.haml
%div.flex.justify-between.flex.h-100.bg-white.py-3.px-3.mb-2
  =link_to root_path do
    %i{class:"fa-solid fa-bars text-black text-lg"}
  %div.flex.gap-3.items-center
    = link_to "#{current_user.first_name&.titleize || "Please add name"}", user_path(current_user.id), class: "text-blue-500 font-bolde"
    %div.flex.items-center
      = button_to destroy_user_session_path, method: :delete, data: {turbo: false}, class: "text-red-500 text-lg font-bold " do
        %i{class:"fa-solid fa-right-from-bracket"}

app/views/shared/_pagination.html.haml
%div.flex.justify-between.text-zinc-800
  %form{action: url, method: :get}
    %select{name: "per_page", class: "form-select rounded-full text-zinc-800 border border-zinc-300 bg-white px-2 py-1 pr-6 hover:border-zinc-400 focus:border-primary dark:border-zinc-450 dark:bg-zinc-700 dark:hover:border-zinc-400 dark:focus:border-accent", data: {controller: "select-and-go", action: "change->select-and-go#choose"}}
      %option.text-zinc-800{value: 10, selected: per_page == '10' ? 'selected' : false}
        10
      %option.text-zinc-800{value: 30, selected: per_page == '30' ? 'selected' : false}
        30
      %option.text-zinc-800{value: 50, selected: per_page == '50' ? 'selected' : false}
        50
      -if (objects&.size || 0) > 50
        %option.text-zinc-800{value: objects.size, selected: per_page == "#{objects.size}" ? 'selected' : false}
          = objects.size
    %span entries
  .flex.flex-col.justify-between.space-y-4.px-4.py-4.sm:flex-row.sm:items-center.sm:space-y-0.sm:px-5
    %div{class: "text-xs+"}
      = "#{pagy.from} - #{pagy.to} of #{pagy.count} entries"

app/views/users/show.html.haml
%div.px-5 
  .block.justify-between.page-header.md:flex.text-zinc-800
    %div
      %h3.font-semibold.text-lg Profile
    %ol.flex.items-center.whitespace-nowrap.min-w-0
      %li{:class => "text-zinc-800 ps-[0.5rem]"}
        %a.flex.items-center.text-zinc-800{class: "hover:text-zinc-800/30  truncate" , :href => "/"}
          Dashboard
          %i.ti.ti-chevrons-right.flex-shrink-0.overflow-visible.rtl:rotate-180{:class => " px-[0.5rem]"}
      %li.text-zinc-800.font-semibold{class: "hover:text-zinc-800 text-zinc-800", "aria-current" => "page", :class => "text-[0.813rem] "} Profile
  .grid.grid-cols-12.gap-x-6
    .xxl:col-span-4.xl:col-span-12.col-span-12.bg-white
      .box.overflow-hidden
        .box-body{:class => "!p-0"}
          .sm:flex.items-start.p-6{class:"bg-gradient-to-r from-slate-500 to-slate-800"}
            %div{class:"h-14 bg-linear-to-t from-sky-500 to-indigo-500"}
              %span.avatar.avatar-xxl.avatar-rounded.online.me-4
                %img{:alt => "", :src => "../assets/images/faces/9.jpg"}/
            .flex-grow.main-profile-info
              .flex.items-center{:class => "!justify-between"}
                %h6.font-semibold.mb-1.text-zinc-800{:class => "text-[1rem]"}= @user.name.titleize
                %div.grid.grid-cols-2.gap-3
                  =link_to edit_user_registration_path ,class: "underline" do
                    Edit Password
                  =link_to edit_user_path, class: "underline" do
                    Edit User
              %p.mb-1{:class => "!text-zinc-800 opacity-[0.7]"} Chief Executive Officer (C.E.O)
              %p.text-zinc-800.mb-6{:class => "text-[0.75rem] opacity-[0.5]"}
                %span.me-4.inline-flex
                  %i.ri-building-line.me-1.align-middle
                  Georgia
                %span.inline-flex
                  %i.ri-map-pin-line.me-1.align-middle
                  Washington D.C
            
             
          .p-6.border-b.border-dashed{:class => "dark:border-defaultborder/10"}
            %p.mb-2.me-6.font-semibold{:class => "text-[.9375rem]"} Contact Information :
            %div{:class => "text-zinc-800/50"}
              %p.mb-2
                %span.avatar.avatar-sm.avatar-rounded.me-2.bg-light{:class => "text-zinc-800"}
                  %i.ri-mail-line.align-middle{:class => "text-[.875rem] text-zinc-800 "}
                =@user.email
              %p.mb-2
                %span.avatar.avatar-sm.avatar-rounded.me-2.bg-light{:class => "text-zinc-800"}
                  %i.ri-phone-line.align-middle{:class => "text-[.875rem] text-zinc-800"}
                +(555) 555-1234
              %p.mb-0
                %span.avatar.avatar-sm.avatar-rounded.me-2.bg-light{:class => "text-zinc-800"}
                  %i.ri-map-pin-line.align-middle{:class => "text-[.875rem] text-zinc-800"}
                MIG-1-11, Monroe Street, Georgetown, Washington D.C, USA,20071
        